export const ADD_SEARCH_TERM = 'ADD_SEARCH_TERM';
export const CLEAR_SEARCH_TERMS = 'CLEAR_SEARCH_TERMS';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const RANDOM_WORD = 'RANDOM_WORD';
